# Generated by Django 4.0.2 on 2022-02-07 19:52

import authentication.utils
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('surname', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Surname')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email_confirmation_token', models.UUIDField(default=uuid.uuid4)),
                ('email_confirmation_token_ttl', models.DateTimeField(default=authentication.utils.get_email_confirmation_token_expiration_time)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DELETED', 'Deleted'), ('UNDER_VERIFICATION', 'Under Verification')], default='UNDER_VERIFICATION', max_length=18, verbose_name='Account Status')),
                ('account_type', models.CharField(choices=[('ADMIN', 'Admin'), ('BARBER', 'Barber'), ('CUSTOMER', 'Customer')], max_length=8, verbose_name='Account Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
