# Generated by Django 4.0.2 on 2022-02-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED'), ('DELETED', 'DELETED'), ('UNDER_VERIFICATION', 'UNDER_VERIFICATION')], default='UNDER_VERIFICATION', max_length=18, verbose_name='Account Status'),
        ),
    ]
