# Generated by Django 4.0.2 on 2022-03-14 16:21

import authentication.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_newsletter',
            field=models.BooleanField(default=False, verbose_name='Accepted Newsletter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Email Confirmation Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token_ttl',
            field=models.DateTimeField(default=authentication.utils.get_email_confirmation_token_expiration_time, verbose_name='Email Confirmation Token TTL'),
        ),
    ]
