# Generated by Django 4.0.2 on 2022-02-13 18:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceunavailability',
            name='start_date',
            field=models.DateField(validators=[core.validators.DateNotInThePastValidator()], verbose_name='Start Date'),
        ),
    ]
