# Generated by Django 4.0.2 on 2022-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_alter_serviceoffer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='barber/service_offers/thumbnail', verbose_name='Barber Thumbnail'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='image',
            field=models.ImageField(blank=True, upload_to='barber/service_offers/image', verbose_name='Barber Image'),
        ),
    ]
