# Generated by Django 4.0.2 on 2022-02-14 15:56

from django.db import migrations

from management import initial_data


class Migration(migrations.Migration):
    '''This migration is irrevertible.'''

    dependencies = [
    ]

    operations = [migrations.RunPython(initial_data.populate_groups)]
