# Generated by Django 4.0.2 on 2022-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed')], default='NEW', max_length=9, verbose_name='Status'),
        ),
    ]
