# Generated by Django 4.0.2 on 2022-02-13 18:12

import core.validators
import customer.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='service_time',
            field=models.DateTimeField(validators=[core.validators.FullOrHalfHourValidator()], verbose_name='Service Time'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='token',
            field=models.CharField(default=customer.utils.generate_short_uuid, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Token'),
        ),
    ]
